package net.mcmaker.command;

import net.mcmaker.registry.NewRegistries;
import net.minecraft.command.impl.AdvancementCommand;
import net.minecraft.command.impl.AttributeCommand;
import net.minecraft.command.impl.BanCommand;
import net.minecraft.command.impl.BanIpCommand;
import net.minecraft.command.impl.BanListCommand;
import net.minecraft.command.impl.BossBarCommand;
import net.minecraft.command.impl.ClearCommand;
import net.minecraft.command.impl.CloneCommand;
import net.minecraft.command.impl.DataPackCommand;
import net.minecraft.command.impl.DeOpCommand;
import net.minecraft.command.impl.DebugCommand;
import net.minecraft.command.impl.DefaultGameModeCommand;
import net.minecraft.command.impl.DifficultyCommand;
import net.minecraft.command.impl.EffectCommand;
import net.minecraft.command.impl.EnchantCommand;
import net.minecraft.command.impl.ExecuteCommand;
import net.minecraft.command.impl.ExperienceCommand;
import net.minecraft.command.impl.FillCommand;
import net.minecraft.command.impl.ForceLoadCommand;
import net.minecraft.command.impl.FunctionCommand;
import net.minecraft.command.impl.GameModeCommand;
import net.minecraft.command.impl.GameRuleCommand;
import net.minecraft.command.impl.GiveCommand;
import net.minecraft.command.impl.HelpCommand;
import net.minecraft.command.impl.KickCommand;
import net.minecraft.command.impl.KillCommand;
import net.minecraft.command.impl.ListCommand;
import net.minecraft.command.impl.LocateBiomeCommand;
import net.minecraft.command.impl.LocateCommand;
import net.minecraft.command.impl.LootCommand;
import net.minecraft.command.impl.MeCommand;
import net.minecraft.command.impl.MessageCommand;
import net.minecraft.command.impl.OpCommand;
import net.minecraft.command.impl.PardonCommand;
import net.minecraft.command.impl.PardonIpCommand;
import net.minecraft.command.impl.ParticleCommand;
import net.minecraft.command.impl.PlaySoundCommand;
import net.minecraft.command.impl.PublishCommand;
import net.minecraft.command.impl.RecipeCommand;
import net.minecraft.command.impl.ReloadCommand;
import net.minecraft.command.impl.SaveAllCommand;
import net.minecraft.command.impl.SaveOffCommand;
import net.minecraft.command.impl.SaveOnCommand;
import net.minecraft.command.impl.SayCommand;
import net.minecraft.command.impl.ScheduleCommand;
import net.minecraft.command.impl.ScoreboardCommand;
import net.minecraft.command.impl.SetBlockCommand;
import net.minecraft.command.impl.SetIdleTimeoutCommand;
import net.minecraft.command.impl.SetWorldSpawnCommand;
import net.minecraft.command.impl.SpawnPointCommand;
import net.minecraft.command.impl.SpectateCommand;
import net.minecraft.command.impl.SpreadPlayersCommand;
import net.minecraft.command.impl.StopCommand;
import net.minecraft.command.impl.StopSoundCommand;
import net.minecraft.command.impl.SummonCommand;
import net.minecraft.command.impl.TagCommand;
import net.minecraft.command.impl.TeamCommand;
import net.minecraft.command.impl.TeamMsgCommand;
import net.minecraft.command.impl.TeleportCommand;
import net.minecraft.command.impl.TellRawCommand;
import net.minecraft.command.impl.TimeCommand;
import net.minecraft.command.impl.TitleCommand;
import net.minecraft.command.impl.TriggerCommand;
import net.minecraft.command.impl.WeatherCommand;
import net.minecraft.command.impl.WhitelistCommand;
import net.minecraft.command.impl.WorldBorderCommand;
import net.minecraft.command.impl.data.DataCommand;
import net.minecraft.test.TestCommand;
import net.minecraft.util.ResourceLocation;

public class NewCommands {
	
	public static final NewCommand ADVANCMENT= register("advancment", new AdvancementCommand());
	public static final NewCommand ATTRIBUTE = register("attribute", new AttributeCommand());
	public static final NewCommand EXECUTE = register("execute", new ExecuteCommand());
	public static final NewCommand BOSS_BAR = register("bossbar", new BossBarCommand());
	public static final NewCommand CLEAR = register("clear", new ClearCommand());
	public static final NewCommand CLONE = register("clone", new CloneCommand());
	public static final NewCommand DATA = register("data", new DataCommand());
	public static final NewCommand DATA_PACK = register("datapack", new DataPackCommand());
	public static final NewCommand DEBUG = register("debug", new DebugCommand());
	public static final NewCommand DEFAULT_GAME_MODE = register("defaultgamemod", new DefaultGameModeCommand());
	public static final NewCommand DIFFICULTY = register("difficulty", new DifficultyCommand());
	public static final NewCommand EFFECT = register("effect", new EffectCommand());
	public static final NewCommand ME = register("me", new MeCommand());
	public static final NewCommand ENCHANT = register("enchant", new EnchantCommand());
	public static final NewCommand EXPERIENCE = register("xp", new ExperienceCommand());
	public static final NewCommand FILL = register("fill", new FillCommand());
	public static final NewCommand FORCE_LOAD = register("forceload", new ForceLoadCommand());
	public static final NewCommand FUNCTION = register("function", new FunctionCommand());
	public static final NewCommand GAME_MODE = register("gamemode", new GameModeCommand());
	public static final NewCommand GAME_RULE = register("gamerule", new GameRuleCommand());
	public static final NewCommand GIVE = register("give", new GiveCommand());
	public static final NewCommand HELP = register("help", new HelpCommand());
	public static final NewCommand KICK = register("kick", new KickCommand());
	public static final NewCommand KILL = register("kill", new KillCommand());
	public static final NewCommand LIST = register("list", new ListCommand());
	public static final NewCommand LOCATE = register("locate", new LocateCommand());
	public static final NewCommand LOCATE_BIOME = register("locate_biome", new LocateBiomeCommand());
	public static final NewCommand LOOT = register("loot", new LootCommand());
	public static final NewCommand MESSAGE = register("message", new MessageCommand());
	public static final NewCommand PARTICLE = register("patricle", new ParticleCommand());
	public static final NewCommand PLAY_SOUND = register("playsound", new PlaySoundCommand());
	public static final NewCommand RELOAD = register("reload", new ReloadCommand());
	public static final NewCommand RECIPE = register("recipe", new RecipeCommand());
	public static final NewCommand REPLACE_ITEM = register("replaceitem", new RecipeCommand());
	public static final NewCommand SAY = register("say", new SayCommand());
	public static final NewCommand SCHEDULE = register("schedule", new ScheduleCommand());
	public static final NewCommand SCOREBOARD = register("scoreboard", new ScoreboardCommand());
	public static final NewCommand SET_BLOCK = register("setblock", new SetBlockCommand());
	public static final NewCommand SPAWN_POINT = register("spawnpoint", new SpawnPointCommand());
	public static final NewCommand SET_WORLD_SPAWN = register("setworldspawn", new SetWorldSpawnCommand());
	public static final NewCommand SPECTATE = register("spectate", new SpectateCommand());
	public static final NewCommand SPREAD_PLAYERS = register("spreadplayers", new SpreadPlayersCommand());
	public static final NewCommand STOP_SOUND = register("stopsound", new StopSoundCommand());
	public static final NewCommand SUMMON = register("summon", new SummonCommand());
	public static final NewCommand TAG = register("tag", new TagCommand());
	public static final NewCommand TEAM = register("team", new TeamCommand());
	public static final NewCommand TEAM_MESSAGE = register("teammsg", new TeamMsgCommand());
	public static final NewCommand TELEPORT = register("teleport", new TeleportCommand());
	public static final NewCommand TELLRAW = register("tellraw", new TellRawCommand());
	public static final NewCommand TIME = register("time", new TimeCommand());
	public static final NewCommand TITLE = register("title", new TitleCommand());
	public static final NewCommand TRIGGER = register("trigger", new TriggerCommand());
	public static final NewCommand WEATHER = register("weather", new WeatherCommand());
	public static final NewCommand WORLD_BORDER = register("worldboarder", new WorldBorderCommand());
	public static final NewCommand TEST = register("test", new TestCommand());
	public static final NewCommand BAN_IP = register("banip", new BanIpCommand());
	public static final NewCommand BAN_LIST = register("banlist", new BanListCommand());
	public static final NewCommand BAN = register("ban", new BanCommand());
	public static final NewCommand DEOP = register("deop", new DeOpCommand());
	public static final NewCommand OP = register("op", new OpCommand());
	public static final NewCommand PARDON = register("pardon", new PardonCommand());
	public static final NewCommand PARDON_IP = register("pardonip", new PardonIpCommand());
	public static final NewCommand SAVE_ALL = register("save-all", new SaveAllCommand());
	public static final NewCommand SAVE_OFF = register("save-off", new SaveOffCommand());
	public static final NewCommand SAVE_ON = register("save-on", new SaveOnCommand());
	public static final NewCommand SET_IDLE_TIMEOUT = register("setidletimeout", new SetIdleTimeoutCommand());
	public static final NewCommand STOP = register("stop", new StopCommand());
	public static final NewCommand WHITELIST = register("whitelist", new WhitelistCommand());
	public static final NewCommand PUBLISH = register("publish", new PublishCommand());
	
	private static NewCommand register(String key, NewCommand command) {
		return NewRegistries.register(NewRegistries.COMMAND, new ResourceLocation(key), command);
	}
	
}